version: '3.9'

services:

  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef
      POSTGRES_USER: app
      POSTGRES_DB: app